### ISSUE TITLE
request failed

### ISSUE THREAD

**Issue by Chrisbitcointalk** [achow101/BitcointalkAccountPricer#5]
Hi,

I've tried to use the account pricer a few times today but I keep getting request failed. 

I took a screenshot. 

[IMG]http://i64.tinypic.com/2s8k0w2.png[/IMG]
‎
Chris! (bitcointalk.org)‎

**Comment by achow101** [comment]
Wait a little bit and then try again. The request fails because of problems fetching the necessary pages from Bitcointalk, which may have temporarily IP banned my server.

**Comment by Chrisbitcointalk** [comment]
The odd thing is, I've tried a few random numbers and they all work. Maybe it's an issue with my profile for some strange reason. I'm 662129.

**Comment by achow101** [comment]
Hmm. Not quite sure what is wrong here. I will try debugging it and see if I can replicate this locally on my computer.

**Comment by achow101** [comment]
Ok, I found the problem. It looks like there is a mismatch between the numbers reported for the number of posts that you have. Your profile lists that you have 147 posts, but in actuality, you have 150. Since the site uses the number of posts reported in the profile for calculating the number of pages to get and the number of slots to put in an array, it runs into an IndexOutOfBounds exception when it gets to the last few posts.
